inherit_from: .rubocop_todo.yml

require: 
- rubocop-rspec

########## Lint / CodeStyle

# This gem is included as part of the `Pluginfile`, which is `required` separately,
# so makes it hard to keep it ordered with the rest of the gems
Gemspec/OrderedDependencies:
  Exclude:
    - 'fastlane-plugin-wpmreleasetoolkit.gemspec'

# Especially for actions and methods like `self.run(params)` it's common to have the argument unused; but that
# comes with the parent class API / contract, so we feel it more readable to avoid the _ unused prefix for those.
Lint/UnusedMethodArgument:
  Enabled: false

########## Metrics / Max Lengths Rules

Metrics/LineLength:
  Max: 300

Metrics/AbcSize:
  Max: 140

Metrics/BlockLength:
  Max: 80

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 300

Metrics/ParameterLists:
  Max: 10

########## Metrics / Complexity

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20
