version: 2.1

orbs:
  ios: wordpress-mobile/ios@1.0

# Common steps reused on various jobs
commands:
  setup_tools:
    description: "Install Homebrew and Ruby dependencies"
    steps:
      - restore_cache:
          name: Restore Homebrew + Ruby Dependencies
          keys:
            - &cache_key brew-dependencies-{{ checksum ".circleci/.brewfile" }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Homebrew dependencies, if neeeded
          command: brew update && xargs brew install --verbose < .circleci/.brewfile

      - run:
          name: Install Ruby dependencies, if neeeded
          command: bundle check --path vendor/bundle || bundle install --with screenshots

      - save_cache:
          name: Cache Homebrew + Ruby Dependencies
          key: *cache_key
          paths:
            - vendor/
            - /usr/local/Cellar

jobs:
  test:
    executor:
      name: ios/default
      xcode-version: "11.2.1"
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      PKG_CONFIG_PATH: "/usr/local/opt/imagemagick@6/lib/pkgconfig"
    steps:
      - checkout
      - setup_tools
      - run: # Compile drawText
          name: Compile drawText
          command: bundle exec rake compile
      - run:
          name: Run rspec and upload coverage report
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      # Save test results for timing analysis
      - store_test_results:
          path: test_results
      
      # Coverage reports are sent to Codecov as part of running `rspec`, not as a CircleCI step.
      # We may wish to change this for consistency.

  gem-push:
    executor:
      name: ios/default
      xcode-version: "11.2.1" # We need an Xcode-enabled CI image to build drawText during gem build
    environment:
      HOMEBREW_NO_AUTO_UPDATE: 1
      PKG_CONFIG_PATH: "/usr/local/opt/imagemagick@6/lib/pkgconfig"
    steps:
      - checkout
      - setup_tools
      - run:
          name: Build gem
          command: gem build fastlane-plugin-wpmreleasetoolkit.gemspec
      - run:
          name: Check the gem is installable
          command: gem install fastlane-plugin-wpmreleasetoolkit-*.gem
      - run:
          name: Push to RubyGems
          command: gem push fastlane-plugin-wpmreleasetoolkit-*.gem

workflows:
  test:
    jobs:
      - test
  release:
    jobs:
      - gem-push:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

