# Nodes with values to reuse in the pipeline.
common_params:
  plugins: &common_plugins
  - &bash_cache automattic/bash-cache#v1.3.2: ~
  # Common environment values to use with the `env` key.
  env: &common_env
    IMAGE_ID: xcode-12.5.1

steps:
  #################
  # Build and Test
  #################
  - label: "🧪 Build and Test"
    key: "test"
    command: |
      echo "--- :beer: Installing Dependencies"
      brew bundle --file .buildkite/.brewfile

      echo "--- :rubygems: Setting up Gems"
      install_gems

      echo "--- :rspec: Run Rspec"
      bundle exec rspec --profile 10 \
        --format RspecJunitFormatter \
        --out test_results/rspec.xml \
        --format progress
    env: *common_env
    plugins: *common_plugins
    agents:
      queue: "mac"